Repository openrewrite/rewrite-testing-frameworks, pull requests merged in 2023-12, with the labels that each got.

#440 Also swap assertNull and assertNotNull argument order
  src/main/java/org/openrewrite/java/testing/cleanup/AssertionsArgumentOrder.java
  src/test/java/org/openrewrite/java/testing/cleanup/AssertionsArgumentOrderTest.java
Labels: enhancement, recipe

#442 Do not change visibility in `UpdateTestAnnotation`; use `TestsShouldNotBePublic` instead
  src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
  src/test/java/org/openrewrite/java/testing/junit5/JUnit5MigrationTest.java
  src/test/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotationTest.java
  src/test/java/org/openrewrite/java/testing/mockito/JunitMockitoUpgradeIntegrationTest.java
Labels: bug

#444 `AddMissingTestBeforeAfterAnnotations` recipe for overridden JUnit test methods
  src/main/java/org/openrewrite/java/testing/junit5/AddMissingTestBeforeAfterAnnotations.java
  src/main/resources/META-INF/rewrite/junit5.yml
  src/test/java/org/openrewrite/java/testing/junit5/AddMissingTestBeforeAfterAnnotationsTest.java
  src/test/java/org/openrewrite/java/testing/junit5/JUnit5MigrationTest.java
Labels: recipe

#445 AddMissingTestBeforeAfterAnnotations is looking for both old and new annotations
  src/main/java/org/openrewrite/java/testing/junit5/AddMissingTestBeforeAfterAnnotations.java
  src/main/resources/META-INF/rewrite/junit5.yml
  src/test/java/org/openrewrite/java/testing/junit5/AddMissingTestBeforeAfterAnnotationsTest.java
Labels: bug, enhancement
