Repository openrewrite/rewrite-testing-frameworks, pull requests merged in 2023-07, with the labels that each got.

#374 Limit `RemoveIsMatcher` to invocations within `assertThat`
  src/main/java/org/openrewrite/java/testing/hamcrest/RemoveIsMatcher.java
  src/test/java/org/openrewrite/java/testing/hamcrest/RemoveIsMatcherTest.java
Labels: bug

#372 Assert instance of migration
  src/main/java/org/openrewrite/java/testing/junit5/AssertTrueInstanceofToAssertInstanceOf.java
  src/test/java/org/openrewrite/java/testing/junit5/AssertTrueInstanceofToAssertInstanceOfTest.java
Labels: recipe

#370 Remove try-catch-fail blocks from unit tests
  src/main/java/org/openrewrite/java/testing/junit5/RemoveTryCatchFailBlocks.java
  src/test/java/org/openrewrite/java/testing/junit5/RemoveTryCatchFailBlocksTest.java
Labels: recipe

#380 Restore now Scanning AnyToNullable, as it does not affect Mockito 2+
  src/main/resources/META-INF/rewrite/mockito.yml
Labels: enhancement

#382 Alek/remove try catch blocks fix
  src/main/java/org/openrewrite/java/testing/junit5/RemoveTryCatchFailBlocks.java
  src/main/resources/META-INF/rewrite/junit5.yml
  src/test/java/org/openrewrite/java/testing/junit5/RemoveTryCatchFailBlocksTest.java
Labels: bug

#384 Migrate assertEquals with array parameter to assertArrayEquals
  src/main/java/org/openrewrite/java/testing/junit5/AssertToAssertions.java
  src/main/resources/META-INF/rewrite/junit5.yml
  src/test/java/org/openrewrite/java/testing/junit5/JUnit5MigrationTest.java
Labels: enhancement

#375 Flatten Hamcrest assertThat allOf
  build.gradle.kts
  src/main/java/org/openrewrite/java/testing/hamcrest/FlattenAllOf.java
  src/main/resources/META-INF/rewrite/hamcrest.yml
  src/test/java/org/openrewrite/java/testing/hamcrest/FlattenAllOfTest.java
  src/test/java/org/openrewrite/java/testing/hamcrest/MigrateHamcrestToAssertJTest.java
Labels: recipe

#388 Replace Hamcrest `is` with AssertJ
  src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestIsMatcherToAssertJ.java
  src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestMatcherToAssertJ.java
  src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestNotMatcherToAssertJ.java
  src/main/java/org/openrewrite/java/testing/hamcrest/RemoveIsMatcher.java
  src/main/resources/META-INF/rewrite/hamcrest.yml
  src/test/java/org/openrewrite/java/testing/hamcrest/HamcrestIsMatcherToAssertJTest.java
Labels: recipe

#389 Reduce duplication and migrate closeTo with three arguments
  src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestMatcherToAssertJ.java
Labels: bug

#386 Use xmlunit-legacy instead of xmlunit
  src/main/resources/META-INF/rewrite/junit5.yml
  src/test/java/org/openrewrite/java/testing/junit5/UseXMLUnitLegacyTest.java
Labels: recipe

#391 Migrate Hamcrest `anyOf` matchers to AssertJ `satisfiesAnyOf` assertions
  src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestAnyOfToAssertJ.java
  src/main/resources/META-INF/rewrite/hamcrest.yml
  src/test/java/org/openrewrite/java/testing/hamcrest/HamcrestAnyOfToAssertJTest.java
Labels: recipe
