Repository openrewrite/rewrite-testing-frameworks, pull requests merged in 2023-11, with the labels that each got.

#420 JMockit to Mockito Recipe - Handle Typed Class Argument Matching and Collections
  src/main/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockito.java
  src/test/java/org/openrewrite/java/testing/jmockit/JMockitToMockitoTest.java
Labels: enhancement, recipe

#424 Remove test prefix with JUnit best practices
  src/main/resources/META-INF/rewrite/junit5.yml
Labels: enhancement

#426 Don't remove `mockStatic()` calls in resources of try-with-resources
  src/main/java/org/openrewrite/java/testing/mockito/PowerMockitoMockStaticToMockito.java
  src/main/resources/META-INF/rewrite/mockito.yml
  src/test/java/org/openrewrite/java/testing/mockito/PowerMockitoMockStaticToMockitoTest.java
Labels: bug

#425 Replace Hamcrest CoreMatchers as well using wildcards
  src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestIsMatcherToAssertJ.java
  src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestMatcherToAssertJ.java
  src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestNotMatcherToAssertJ.java
  src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestOfMatchersToAssertJ.java
  src/main/java/org/openrewrite/java/testing/hamcrest/RemoveIsMatcher.java
  src/test/java/org/openrewrite/java/testing/hamcrest/HamcrestMatcherToAssertJTest.java
Labels: recipe

#430 Fixes broken testcontainer dependencies after JUnit4to5Migration
  src/main/resources/META-INF/rewrite/junit5.yml
  src/test/java/org/openrewrite/java/testing/junit5/JUnit5MigrationTest.java
Labels: bug

#433 Rewrite testcontainers to use explicit image and version
  build.gradle.kts
  src/main/java/org/openrewrite/java/testing/testcontainers/ExplicitContainerImage.java
  src/main/java/org/openrewrite/java/testing/testcontainers/package-info.java
  src/main/resources/META-INF/rewrite/testcontainers.yml
  src/test/java/org/openrewrite/java/testing/testcontainers/ExplicitContainerImageTest.java
  src/test/java/org/openrewrite/java/testing/testcontainers/TestcontainersBestPracticesTest.java
Labels: recipe
