Repository openrewrite/rewrite-testing-frameworks, pull requests merged in 2023-08, with the labels that each got.

#393 Fix problem with incorrectly removed Mockito imports
  src/main/java/org/openrewrite/java/testing/mockito/CleanupMockitoImports.java
  src/test/java/org/openrewrite/java/testing/mockito/CleanupMockitoImportsTest.java
Labels: bug

#385 Simplify chained AssertJ assertions
  src/main/java/org/openrewrite/java/testing/assertj/SimplifyChainedAssertJAssertion.java
  src/main/java/org/openrewrite/java/testing/assertj/UseExplicitContains.java
  src/main/java/org/openrewrite/java/testing/assertj/UseExplicitIsEmpty.java
  src/main/java/org/openrewrite/java/testing/assertj/UseExplicitSize.java
  src/main/resources/META-INF/rewrite/assertj.yml
  src/test/java/org/openrewrite/java/testing/assertj/MigrateChainedAssertToAssertJTest.java
  src/test/java/org/openrewrite/java/testing/assertj/SimplifyChainedAssertJAssertionTest.java
  src/test/java/org/openrewrite/java/testing/assertj/UseExplicitContainsTest.java
  src/test/java/org/openrewrite/java/testing/assertj/UseExplicitIsEmptyTest.java
  src/test/java/org/openrewrite/java/testing/assertj/UseExplicitSizeTest.java
Labels: recipe

#396 support for `allOf` hamcrest matcher
  src/main/java/org/openrewrite/java/testing/hamcrest/FlattenAllOf.java
  src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestOfMatchersToAssertJ.java
  src/main/resources/META-INF/rewrite/hamcrest.yml
  src/test/java/org/openrewrite/java/testing/hamcrest/FlattenAllOfTest.java
  src/test/java/org/openrewrite/java/testing/hamcrest/HamcrestOfMatchersToAssertJTest.java
  src/test/java/org/openrewrite/java/testing/hamcrest/MigrateHamcrestToAssertJTest.java
Labels: enhancement
