Repository openrewrite/rewrite-testing-frameworks, pull requests merged in 2024-12, with the labels that each got.

#648 Add AssertJ dependency if using Hamcrest
  src/main/resources/META-INF/rewrite/hamcrest.yml
  src/test/java/org/openrewrite/java/testing/hamcrest/MigrateHamcrestToAssertJTest.java
Labels: bug

#639 Migration from easymock to mockito
  build.gradle.kts
  src/main/java/org/openrewrite/java/testing/easymock/EasyMockVerifyToMockitoVerify.java
  src/main/java/org/openrewrite/java/testing/easymock/RemoveExtendsEasyMockSupport.java
  src/main/java/org/openrewrite/java/testing/easymock/package-info.java
  src/main/java/org/openrewrite/java/testing/mockito/NoInitializationForInjectMock.java
  src/main/resources/META-INF/rewrite/classpath/mockito-core-5.14.2.jar
  src/main/resources/META-INF/rewrite/easymock.yml
  src/main/resources/META-INF/rewrite/mockito.yml
  src/test/java/org/openrewrite/java/testing/easymock/EasyMockToMockitoTest.java
  src/test/java/org/openrewrite/java/testing/easymock/EasyMockVerifyToMockitoVerifyTest.java
  src/test/java/org/openrewrite/java/testing/easymock/RemoveExtendsEasyMockSupportTest.java
  src/test/java/org/openrewrite/java/testing/mockito/NoInitializationForInjectMockTest.java
Labels: easymock

#343 Migrate Hamcrest to JUnit 5
  src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestInstanceOfToJUnit5.java
  src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestMatcherToJUnit5.java
  src/main/java/org/openrewrite/java/testing/hamcrest/RemoveNotMatcherVisitor.java
  src/main/resources/META-INF/rewrite/hamcrest.yml
  src/test/java/org/openrewrite/java/testing/hamcrest/HamcrestInstanceOfToJUnit5Test.java
  src/test/java/org/openrewrite/java/testing/hamcrest/HamcrestMatcherToJUnit5Test.java
  src/test/java/org/openrewrite/java/testing/hamcrest/MigrateHamcrestToJUnitTest.java
  src/test/java/org/openrewrite/java/testing/hamcrest/RemoveNotMatcherTest.java
Labels: recipe

#520 Add recipes to migrate from TestNG to AssertJ
  build.gradle.kts
  src/main/java/org/openrewrite/java/testing/testng/TestNgAssertEqualsToAssertThat.java
  src/main/java/org/openrewrite/java/testing/testng/TestNgAssertNotEqualsToAssertThat.java
  src/main/resources/META-INF/rewrite/assertj.yml
  src/main/resources/META-INF/rewrite/testng.yml
  src/test/java/org/openrewrite/java/testing/testng/TestNgToAssertJTest.java
Labels: recipe

#632 Migrate Jmockit VerificationsInOrder to Mockito
  src/main/java/org/openrewrite/java/testing/jmockit/ArgumentMatchersRewriter.java
  src/main/java/org/openrewrite/java/testing/jmockit/JMockitAnnotatedArgumentToMockito.java
  src/main/java/org/openrewrite/java/testing/jmockit/JMockitBlockRewriter.java
  src/main/java/org/openrewrite/java/testing/jmockit/JMockitBlockToMockito.java
  src/main/java/org/openrewrite/java/testing/jmockit/JMockitBlockType.java
  src/main/java/org/openrewrite/java/testing/jmockit/JMockitMockUpToMockito.java
  src/main/java/org/openrewrite/java/testing/jmockit/JMockitUtils.java
  src/test/java/org/openrewrite/java/testing/jmockit/JMockitVerificationsInOrderToMockitoTest.java
  src/test/java/org/openrewrite/java/testing/jmockit/JMockitVerificationsToMockitoTest.java
Labels: enhancement, recipe

#604 AssertJ assertions not collapsed on Integer
  src/main/java/org/openrewrite/java/testing/assertj/CollapseConsecutiveAssertThatStatements.java
  src/test/java/org/openrewrite/java/testing/assertj/CollapseConsecutiveAssertThatStatementsTest.java
Labels: enhancement

#655 Add recipe for replacing deprecated method AbstractDateAssert
  build.gradle.kts
  src/main/java/org/openrewrite/java/testing/assertj/IsEqualToIgnoringMillisToIsCloseTo.java
  src/main/resources/META-INF/rewrite/assertj.yml
  src/test/java/org/openrewrite/java/testing/assertj/IsEqualToIgnoringMillisToIsCloseToTest.java
Labels: recipe, assertj

#654 Add recipes for migrating Arquillian from JUnit 4 to JUnit 5.
  build.gradle.kts
  src/main/java/org/openrewrite/java/testing/arquillian/ReplaceArquillianInSequenceAnnotation.java
  src/main/java/org/openrewrite/java/testing/arquillian/package-info.java
  src/main/resources/META-INF/rewrite/arquillian.yml
  src/main/resources/META-INF/rewrite/junit5.yml
  src/test/java/org/openrewrite/java/testing/arquillian/ArquillianJUnit4ToArquillianJunit5Test.java
  src/test/java/org/openrewrite/java/testing/arquillian/ReplaceArquillianInSequenceAnnotationTest.java
Labels: recipe

#656 Add `Mockito1to5MigrationTest` to verify dependencies are upgraded
  src/test/java/org/openrewrite/java/testing/mockito/Mockito1to5MigrationTest.java
Labels: test provided
