Repository openrewrite/rewrite-testing-frameworks, pull requests merged in 2024-07, with the labels that each got.

#540 Migrate JMockit Verifications to Mockito
  src/main/java/org/openrewrite/java/testing/jmockit/ArgumentMatchersRewriter.java
  src/main/java/org/openrewrite/java/testing/jmockit/JMockitBlockRewriter.java
  src/main/java/org/openrewrite/java/testing/jmockit/JMockitBlockToMockito.java
  src/main/java/org/openrewrite/java/testing/jmockit/JMockitBlockType.java
  src/main/java/org/openrewrite/java/testing/jmockit/JMockitUtils.java
  src/main/java/org/openrewrite/java/testing/jmockit/SetupStatementsRewriter.java
  src/main/resources/META-INF/rewrite/jmockit.yml
  src/test/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockitoTest.java
  src/test/java/org/openrewrite/java/testing/jmockit/JMockitVerificationsToMockitoTest.java
Labels: enhancement

#543 Skip RemoveTestPrefix when calling a similarly named method
  src/main/java/org/openrewrite/java/testing/cleanup/RemoveTestPrefix.java
  src/test/java/org/openrewrite/java/testing/cleanup/RemoveTestPrefixTest.java
Labels: bug

#548 More best pratices for AssertJ
  src/main/java/org/openrewrite/java/testing/assertj/IsEqualToBoolean.java
  src/main/resources/META-INF/rewrite/assertj.yml
  src/test/java/org/openrewrite/java/testing/assertj/IsEqualToBooleanTest.java
  src/test/java/org/openrewrite/java/testing/assertj/IsEqualToEmptyStringTest.java
  src/test/java/org/openrewrite/java/testing/assertj/MigrateChainedAssertToAssertJTest.java
Labels: enhancement, recipe

#549 JMockit NonStrictExpectations with times should be migrated to default when without lenient(), refactor
  src/main/java/org/openrewrite/java/testing/jmockit/JMockitBlockRewriter.java
  src/test/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockitoTest.java
  src/test/java/org/openrewrite/java/testing/jmockit/JMockitNonStrictExpectationsToMockitoTest.java
Labels: enhancement

#554 Simplify toString assertion
  src/main/resources/META-INF/rewrite/assertj.yml
  src/main/resources/META-INF/rewrite/junit5.yml
  src/test/java/org/openrewrite/java/testing/assertj/MigrateChainedAssertToAssertJTest.java
  src/test/java/org/openrewrite/java/testing/junit5/CleanupAssertionsTest.java
  src/test/java/org/openrewrite/java/testing/junit5/UseXMLUnitLegacyTest.java
Labels: recipe

#555 ExpectedExceptionToAssertThrows should not wrap single statement
  src/main/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrows.java
  src/test/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrowsTest.java
Labels: enhancement
