Repository openrewrite/rewrite-testing-frameworks, pull requests merged in 2024-05, with the labels that each got.

#514 Added to notMatchers
  src/main/resources/META-INF/rewrite/hamcrest.yml
Labels: enhancement, recipe

#516 AssertToAssertions should only convert methods from exact class
  src/main/java/org/openrewrite/java/testing/junit5/AssertToAssertions.java
  src/test/java/org/openrewrite/java/testing/junit5/AssertToAssertionsTest.java
Labels: bug

#517 Only upgrade maven-surefire-plugin on older Maven versions
  src/main/resources/META-INF/rewrite/junit5.yml
  src/test/java/org/openrewrite/java/testing/junit5/JUnit5MigrationTest.java
Labels: bug, enhancement, recipe
