Repository openrewrite/rewrite-testing-frameworks, pull requests merged in 2024-06, with the labels that each got.

#523 Migrate all Hamcrest matchers from core package
  src/main/resources/META-INF/rewrite/hamcrest.yml
  src/test/java/org/openrewrite/java/testing/hamcrest/MigrateHamcrestToAssertJTest.java
Labels: bug, recipe

#525 Idiomatic AssertJ assertions for empty Strings
  src/main/java/org/openrewrite/java/testing/assertj/IsEqualToEmptyString.java
  src/main/resources/META-INF/rewrite/assertj.yml
  src/test/java/org/openrewrite/java/testing/assertj/IsEqualToEmptyStringTest.java
Labels: recipe

#528 Add Kotlin support for Junit 5 recipes 1: CleanupJUnitImports
  build.gradle.kts
  src/main/java/org/openrewrite/java/testing/junit5/CleanupJUnitImports.java
  src/test/java/org/openrewrite/java/testing/junit5/CleanupJUnitImportsTest.java
Labels: bug

#527 Add Picnic AssertJ rules to AssertJ best practices
  build.gradle.kts
  src/main/java/org/openrewrite/java/testing/assertj/IsEqualToEmptyString.java
  src/main/resources/META-INF/rewrite/assertj.yml
  src/test/java/org/openrewrite/java/testing/assertj/AssertJBestPracticesTest.java
Labels: enhancement

#531 Drop Java 17 requirement through rewrite-third-party
  build.gradle.kts
  src/main/java/org/openrewrite/java/testing/assertj/IsEqualToEmptyString.java
  src/main/resources/META-INF/rewrite/assertj.yml
Labels: bug, dependencies

#530 Jmockit Expectations with no times or result should be transformed to Mockito verify statement
  src/main/java/org/openrewrite/java/testing/jmockit/ExpectationsBlockRewriter.java
  src/test/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockitoTest.java
Labels: bug, enhancement, recipe

#532 Rewrite both JMockit `@Mocked` and `@Injectable` annotated arguments
  src/main/java/org/openrewrite/java/testing/jmockit/JMockitAnnotatedArgumentToMockito.java
  src/main/java/org/openrewrite/java/testing/jmockit/JMockitMockedVariableToMockito.java
  src/main/java/org/openrewrite/java/testing/jmockit/package-info.java
  src/main/resources/META-INF/rewrite/jmockit.yml
  src/test/java/org/openrewrite/java/testing/jmockit/JMockitAnnotatedArgumentToMockitoTest.java
Labels: enhancement, recipe

#539 Add a NoMissingTypes Precondition to CleanupMockitoImports
  build.gradle.kts
  src/main/java/org/openrewrite/java/testing/mockito/CleanupMockitoImports.java
  src/test/java/org/openrewrite/java/testing/mockito/CleanupMockitoImportsTest.java
Labels: bug
