Repository openrewrite/rewrite-testing-frameworks, pull requests merged in 2024-09, with the labels that each got.

#588 `PowerMockitoMockStaticToMockito` duplicates variables and methods when static nested class is involved
  src/main/java/org/openrewrite/java/testing/mockito/PowerMockitoMockStaticToMockito.java
  src/test/java/org/openrewrite/java/testing/mockito/PowerMockitoMockStaticToMockitoTest.java
Labels: bug

#592 Do not perform `JUnit4to5Migration` where TestNG is used
  src/main/resources/META-INF/rewrite/junit5.yml
Labels: bug

#593 Add `MockRestServiceServer.verify` to default assertions
  build.gradle.kts
  src/main/java/org/openrewrite/java/testing/cleanup/TestsShouldIncludeAssertions.java
  src/test/java/org/openrewrite/java/testing/cleanup/TestsShouldIncludeAssertionsTest.java
  src/test/resources/META-INF/rewrite/classpath/spring-test-6.1.12.jar
Labels: enhancement, good first issue

#590 Move Junit 5 assertThrows to last statement in lamdba
  src/main/java/org/openrewrite/java/testing/junit5/AssertThrowsOnLastStatement.java
  src/test/java/org/openrewrite/java/testing/junit5/AssertThrowsOnLastStatementTest.java
Labels: enhancement

#594 Add recipes for negative variants of startsWith, endsWith, and matches
  src/main/resources/META-INF/rewrite/assertj.yml
  src/test/java/org/openrewrite/java/testing/assertj/SimplifyChainedAssertJAssertionsTest.java
Labels: recipe

#596 Handle multiple blocks in JMockit Expectations
  src/main/java/org/openrewrite/java/testing/jmockit/JMockitUtils.java
  src/main/java/org/openrewrite/java/testing/jmockit/SetupStatementsRewriter.java
  src/test/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockitoTest.java
Labels: bug, enhancement

#600 When upgrading mockito also upgrade potential byte buddy dependencies
  src/main/resources/META-INF/rewrite/mockito.yml
  src/test/java/org/openrewrite/java/testing/mockito/MockitoInlineToCoreTest.java
Labels: enhancement

#602 Include `ReplacePowerMockito` with `Mockito1to3Migration` again
  src/main/resources/META-INF/rewrite/mockito.yml
  src/main/resources/META-INF/rewrite/powermockito.yml
  src/test/java/org/openrewrite/java/testing/mockito/RemoveMockitoSettingsTest.java
Labels: enhancement

#601 Refactor `Mockito.when` on static (non mock) to try with resource
  src/main/java/org/openrewrite/java/testing/mockito/MockitoWhenOnStaticToMockStatic.java
  src/main/resources/META-INF/rewrite/mockito.yml
  src/test/java/org/openrewrite/java/testing/mockito/MockitoWhenOnStaticToMockStaticTest.java
Labels: enhancement

#612 `PowerMockitoMockStaticToMockito` should not remove existing `mockStatic` initializer
  src/main/java/org/openrewrite/java/testing/mockito/PowerMockitoMockStaticToMockito.java
  src/test/java/org/openrewrite/java/testing/mockito/PowerMockitoMockStaticToMockitoTest.java
Labels: bug
