Repository openrewrite/rewrite-testing-frameworks, pull requests merged in 2024-10, with the labels that each got.

#610 Migrate JMockit block to Mockito which contains redundant "this" prefix for arg matcher and migrate array as parameter for any
  src/main/java/org/openrewrite/java/testing/jmockit/ArgumentMatchersRewriter.java
  src/test/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockitoTest.java
  src/test/java/org/openrewrite/java/testing/jmockit/JMockitVerificationsToMockitoTest.java
Labels: bug, enhancement

#615 Add recipe for replacing unnecesary Mockito#eq with direct parameters
  src/main/java/org/openrewrite/java/testing/mockito/SimplifyMockitoVerifyWhenGiven.java
  src/main/resources/META-INF/rewrite/mockito.yml
  src/test/java/org/openrewrite/java/testing/mockito/SimplifyMockitoVerifyWhenGivenTest.java
Labels: recipe

#623 Add `@MockitoSettings(strictness = ...)` based on how Mockito is used, not based on version alone
  src/main/java/org/openrewrite/java/testing/junit5/MockitoJUnitToMockitoExtension.java
  src/test/java/org/openrewrite/java/testing/mockito/MockitoJUnitToMockitoExtensionTest.java
Labels: bug

#625 Drop RetainStrictnessWarn; replaced with #623
  src/main/java/org/openrewrite/java/testing/mockito/RetainStrictnessWarn.java
  src/main/resources/META-INF/rewrite/mockito.yml
  src/test/java/org/openrewrite/java/testing/mockito/RetainStrictnessWarnTest.java
Labels: recipe

#629 SimplifyChainedAssertJAssertion drops method calls in replacement
  src/main/java/org/openrewrite/java/testing/assertj/SimplifyChainedAssertJAssertion.java
  src/test/java/org/openrewrite/java/testing/assertj/SimplifyChainedAssertJAssertionTest.java
Labels: bug, assertj
