Repository openrewrite/rewrite-testing-frameworks, pull requests merged in 2024-08, with the labels that each got.

#557 Add unit tests for JMockit Delegate to mockito migration. Also add test case for comments
  src/test/java/org/openrewrite/java/testing/jmockit/JMockitDelegateToMockitoTest.java
  src/test/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockitoTest.java
Labels: documentation, recipe

#558 Convert `assertTrue(false, String)` and `assertFalse(true, String)` with `fail(String)`
  .gitignore
  build.gradle.kts
  src/main/java/org/openrewrite/java/testing/cleanup/AssertLiteralBooleanToFail.java
  src/test/java/org/openrewrite/java/testing/cleanup/AssertLiteralBooleanToFailTest.java
Labels: recipe

#562 Avoid duplicate before/after annotations in JUnit 3 to 5
  src/main/java/org/openrewrite/java/testing/junit5/MigrateJUnitTestCase.java
  src/test/java/org/openrewrite/java/testing/junit5/MigrateJUnitTestCaseTest.java
Labels: bug

#564 Remove throws from method that adopts `assertThrows`
  src/main/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrows.java
  src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
  src/test/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrowsTest.java
  src/test/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotationTest.java
Labels: enhancement

#566 Dont convert try catch fail when return
  src/main/java/org/openrewrite/java/testing/junit5/RemoveTryCatchFailBlocks.java
  src/test/java/org/openrewrite/java/testing/junit5/RemoveTryCatchFailBlocksTest.java
Labels: bug

#559 Use error-prone-contrib AssertJ recipes
  build.gradle.kts
  src/main/resources/META-INF/rewrite/assertj.yml
Labels: enhancement, dependencies, recipe

#556 Chained AssertJ assertions should be simplified to the corresponding dedicated assertion
  src/main/java/org/openrewrite/java/testing/assertj/IsEqualToBoolean.java
  src/main/java/org/openrewrite/java/testing/assertj/IsEqualToEmptyString.java
  src/main/java/org/openrewrite/java/testing/assertj/SimplifyAssertJAssertion.java
  src/main/java/org/openrewrite/java/testing/assertj/SimplifyChainedAssertJAssertion.java
  src/main/resources/META-INF/rewrite/assertj.yml
  src/test/java/org/openrewrite/java/testing/assertj/AssertJBestPracticesTest.java
  src/test/java/org/openrewrite/java/testing/assertj/IsEqualToBooleanTest.java
  src/test/java/org/openrewrite/java/testing/assertj/IsEqualToEmptyStringTest.java
  src/test/java/org/openrewrite/java/testing/assertj/SimplifyAssertJAssertionTest.java
  src/test/java/org/openrewrite/java/testing/assertj/SimplifyChainedAssertJAssertionTest.java
  src/test/java/org/openrewrite/java/testing/assertj/SimplifyChainedAssertJAssertionWithOptionalTest.java
  src/test/java/org/openrewrite/java/testing/assertj/SimplifyChainedAssertJAssertionsTest.java
Labels: enhancement, recipe

#570 Context free SimplifyAssertJAssertion
  src/main/java/org/openrewrite/java/testing/assertj/SimplifyAssertJAssertion.java
Labels: enhancement

#582 Convert lambda block to expression after adopting `assertThrows`
  src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertThrowsToAssertExceptionType.java
  src/main/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrows.java
  src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
  src/test/java/org/openrewrite/java/testing/assertj/JUnitAssertThrowsToAssertExceptionTypeTest.java
  src/test/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrowsTest.java
  src/test/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotationTest.java
Labels: enhancement

#577 Only add `hamcrest-junit` dependency when using `assertThat` or `assumeThat`
  src/main/java/org/openrewrite/java/testing/junit5/AddHamcrestJUnitDependency.java
  src/main/resources/META-INF/rewrite/junit5.yml
  src/test/java/org/openrewrite/java/testing/junit5/AddHamcrestJUnitDependencyTest.java
Labels: bug

#392 Collapse consecutive `assertThat` statements (#373)
  src/main/java/org/openrewrite/java/testing/assertj/CollapseConsecutiveAssertThatStatements.java
  src/main/resources/META-INF/rewrite/assertj.yml
  src/test/java/org/openrewrite/java/testing/assertj/CollapseConsecutiveAssertThatStatementsTest.java
Labels: recipe

#586 Add JUnit Jupiter dependency to the right scope
  src/main/java/org/openrewrite/java/testing/junit5/AddJupiterDependencies.java
  src/test/java/org/openrewrite/java/testing/junit5/AddJupiterDependenciesTest.java
Labels: enhancement

#584 Retain Mockito Strictness WARN when switching to JUnit 5 through `@MockitoSettings(strictness = Strictness.WARN)`
  src/main/java/org/openrewrite/java/testing/mockito/RetainStrictnessWarn.java
  src/main/resources/META-INF/rewrite/mockito.yml
  src/test/java/org/openrewrite/java/testing/mockito/RetainStrictnessWarnTest.java
Labels: enhancement
