Repository openrewrite/rewrite-testing-frameworks, pull requests merged in 2024-11, with the labels that each got.

#599 Add JMockit's MockUp to Mockito migration
  src/main/java/org/openrewrite/java/testing/jmockit/JMockitMockUpToMockito.java
  src/main/java/org/openrewrite/java/testing/mockito/MockitoUtils.java
  src/main/java/org/openrewrite/java/testing/mockito/PowerMockitoMockStaticToMockito.java
  src/main/resources/META-INF/rewrite/jmockit.yml
  src/test/java/org/openrewrite/java/testing/jmockit/JMockitMockUpToMockitoTest.java
  src/test/java/org/openrewrite/java/testing/jmockit/JMockitNonStrictExpectationsToMockitoTest.java
  src/test/java/org/openrewrite/java/testing/jmockit/JMockitTestUtils.java
Labels: enhancement, recipe

#627 Initial support for DbRider migration from junit4 to junit5
  build.gradle.kts
  src/main/java/org/openrewrite/java/testing/dbrider/ExecutionListenerToDbRiderAnnotation.java
  src/main/java/org/openrewrite/java/testing/dbrider/package-info.java
  src/main/resources/META-INF/rewrite/classpath/rider-junit5-1.44.0.jar
  src/main/resources/META-INF/rewrite/dbrider.yml
  src/main/resources/META-INF/rewrite/junit5.yml
  src/test/java/org/openrewrite/java/testing/dbrider/ExecutionListenerToDbRiderAnnotationUnitTest.java
  src/test/resources/META-INF/rewrite/classpath/rider-spring-1.18.0.jar
Labels: recipe

#606 `assertInstanceOf` not converted from JUnit5 to assertJ
  src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertInstanceOfToAssertThat.java
  src/main/resources/META-INF/rewrite/assertj.yml
  src/test/java/org/openrewrite/java/testing/assertj/AssertJBestPracticesTest.java
  src/test/java/org/openrewrite/java/testing/assertj/JUnitAssertInstanceOfToAssertThatTest.java
Labels: good first issue, recipe

#631 Add `VerifyZeroToNoMoreInteractions` for Mockito 2
  src/main/java/org/openrewrite/java/testing/mockito/VerifyZeroToNoMoreInteractions.java
  src/main/resources/META-INF/rewrite/mockito.yml
  src/test/java/org/openrewrite/java/testing/mockito/VerifyZeroToNoMoreInteractionsTest.java
Labels: bug, recipe, mockito

#635 Added handling of org.mockito.Mockito.eq(..) when simplifying mockito matchers
  src/main/java/org/openrewrite/java/testing/mockito/SimplifyMockitoVerifyWhenGiven.java
  src/test/java/org/openrewrite/java/testing/mockito/SimplifyMockitoVerifyWhenGivenTest.java
Labels: bug, mockito

#633 Update AssertJ recipes to current recipe code style
  src/main/java/org/openrewrite/java/testing/assertj/AdoptAssertJDurationAssertions.java
  src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertArrayEqualsToAssertThat.java
  src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertEqualsToAssertThat.java
  src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertFalseToAssertThat.java
  src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertInstanceOfToAssertThat.java
  src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertNotEqualsToAssertThat.java
  src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertNotNullToAssertThat.java
  src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertNullToAssertThat.java
  src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertSameToAssertThat.java
  src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertThrowsToAssertExceptionType.java
  src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertTrueToAssertThat.java
  src/main/java/org/openrewrite/java/testing/assertj/JUnitFailToAssertJFail.java
  src/main/java/org/openrewrite/java/testing/assertj/SimplifyAssertJAssertion.java
  src/main/java/org/openrewrite/java/testing/assertj/SimplifyChainedAssertJAssertion.java
  src/test/java/org/openrewrite/java/testing/assertj/JUnitAssertThrowsToAssertExceptionTypeTest.java
Labels: recipe

#642 Use JUnit5's `assertSame` or `assertNotSame` instead of `assertTrue(... == ...)`
  src/main/java/org/openrewrite/java/testing/junit5/UseAssertSame.java
  src/test/java/org/openrewrite/java/testing/junit5/UseAssertSameTest.java
Labels: recipe

#643 Move HtmlUnit migrations to rewrite-testing-frameworks
  build.gradle.kts
  src/main/resources/META-INF/rewrite/htmlunit.yml
  src/test/java/org/openrewrite/java/testing/htmlunit/UpgradeHtmlUnit3Test.java
Labels: recipe
