Repository openrewrite/rewrite-testing-frameworks, pull requests merged in 2024-02, with the labels that each got.

#474 Add more simplifications
  src/main/resources/META-INF/rewrite/assertj.yml
  src/test/java/org/openrewrite/java/testing/assertj/SimplifyChainedAssertJAssertionTest.java
  src/test/java/org/openrewrite/java/testing/assertj/SimplifyChainedAssertJAssertionWithOptionalTest.java
Labels: recipe

#476 Limit AssertTrueNullToAssertNull applicability
  src/main/java/org/openrewrite/java/testing/cleanup/AssertFalseNullToAssertNotNull.java
  src/main/java/org/openrewrite/java/testing/cleanup/AssertTrueNullToAssertNull.java
  src/test/java/org/openrewrite/java/testing/cleanup/AssertFalseNullToAssertNotNullTest.java
  src/test/java/org/openrewrite/java/testing/cleanup/AssertTrueNullToAssertNullTest.java
Labels: bug

#478 Also remove exclusion from spring-boot-testcontainers
  src/main/resources/META-INF/rewrite/junit5.yml
  src/test/java/org/openrewrite/java/testing/junit5/JUnit5MigrationTest.java
Labels: bug

#480 `JUnitAssertEqualsToAssertThat` skipped adding `assertThat` import for custom classes
  src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertEqualsToAssertThat.java
  src/test/java/org/openrewrite/java/testing/assertj/JUnitAssertEqualsToAssertThatTest.java
Labels: bug

#481 JMockit to Mockito Recipe - Rewrite JMockit Mocked Variable to Mockito statements
  src/main/java/org/openrewrite/java/testing/jmockit/JMockitMockedVariableToMockito.java
  src/main/resources/META-INF/rewrite/jmockit.yml
  src/test/java/org/openrewrite/java/testing/jmockit/JMockitMockedVariableToMockitoTest.java
Labels: recipe

#484 don't use TempDirNonFinal on method parameters
  src/main/java/org/openrewrite/java/testing/junit5/TempDirNonFinal.java
  src/test/java/org/openrewrite/java/testing/junit5/TempDirNonFinalTest.java
Labels: bug

#485 JMockit to Mockito Recipe - `eq` Support, Better Type Propagation, and Error Handling
  src/main/java/org/openrewrite/java/testing/jmockit/ArgumentMatchersRewriter.java
  src/main/java/org/openrewrite/java/testing/jmockit/ExpectationsBlockRewriter.java
  src/main/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockito.java
  src/test/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockitoTest.java
Labels: bug, enhancement
