Repository openrewrite/rewrite-testing-frameworks, pull requests merged in 2025-05, with the labels that each got.

#714 Fix Incorrect Migration of TemporaryFolder.newFile in TemporaryFolderToTmpDir Recipe
  src/main/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDir.java
  src/main/resources/META-INF/rewrite/examples.yml
  src/test/java/org/openrewrite/java/testing/junit5/JUnit5BestPracticesTest.java
  src/test/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDirTest.java
Labels: enhancement

#717 Fix JunitParams to Parameterized by recursively updating referenced method to static
  src/main/java/org/openrewrite/java/testing/junit5/JUnitParamsRunnerToParameterized.java
  src/test/java/org/openrewrite/java/testing/junit5/JUnitParamsRunnerToParameterizedTest.java
Labels: enhancement

#720 Handle non-@Rule TemporaryFolder fields
  src/main/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDir.java
  src/main/resources/META-INF/rewrite/examples.yml
  src/test/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDirTest.java
Labels: enhancement, recipe, junit

#734 Added support for generic instanceof checks in `AssertTrueInstanceofToAssertInstanceOf` recipe
  src/main/java/org/openrewrite/java/testing/junit5/AssertTrueInstanceofToAssertInstanceOf.java
  src/test/java/org/openrewrite/java/testing/junit5/AssertTrueInstanceofToAssertInstanceOfTest.java
Labels: bug, junit

#721 ExpectedExceptionToAssertThrows: Handle branching and var usage in except methods
  src/main/java/org/openrewrite/java/testing/junit5/EnvironmentVariables.java
  src/main/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrows.java
  src/main/resources/META-INF/rewrite/classpath.tsv.zip
  src/test/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrowsTest.java
Labels: enhancement, recipe
